"""
Central environment variable reads for Seed.

Canonical names use the ``SEED_*`` prefix. ``CODEAGENT_*`` names are still read as
fallback aliases (deprecated for external integrations; may be removed in a major release).
"""

from __future__ import annotations

import os
from typing import Tuple


def pick_nonempty(*keys: str) -> str:
    """First defined env var whose value is non-empty after strip."""
    for k in keys:
        raw = os.environ.get(k)
        if raw is not None and str(raw).strip():
            return str(raw).strip()
    return ""


def pick_default(default: str, *keys: str) -> str:
    """First key present in ``os.environ`` (value may be empty); else ``default``."""
    for k in keys:
        if k in os.environ:
            return os.environ[k]
    return default


def any_nonempty(*keys: str) -> bool:
    """True if any listed key has a non-empty stripped value."""
    return any((os.environ.get(k) or "").strip() for k in keys)


def env_truthy(*keys: str, default: str = "0") -> bool:
    """True if the first present key among ``keys`` is truthy (1/true/on/yes)."""
    val = pick_default(default, *keys).strip().lower()
    return val in ("1", "true", "yes", "on")


# --- Canonical tuples (SEED first, CODEAGENT fallback) ---

PROJECT_ROOT: Tuple[str, ...] = ("SEED_PROJECT_ROOT", "CODEAGENT_PROJECT_ROOT")

LLM_API_KEY: Tuple[str, ...] = ("SEED_LLM_API_KEY", "CODEAGENT_LLM_API_KEY")
LLM_AUTH_SCHEME: Tuple[str, ...] = ("SEED_LLM_AUTH_SCHEME", "CODEAGENT_LLM_AUTH_SCHEME")
LLM_MAX_TOKENS: Tuple[str, ...] = ("SEED_LLM_MAX_TOKENS", "CODEAGENT_LLM_MAX_TOKENS")
LLM_NO_TOPK: Tuple[str, ...] = ("SEED_LLM_NO_TOPK", "CODEAGENT_LLM_NO_TOPK")
LLM_ENABLE_THINKING: Tuple[str, ...] = ("SEED_LLM_ENABLE_THINKING", "CODEAGENT_LLM_ENABLE_THINKING")
LLM_REASONING_EFFORT: Tuple[str, ...] = ("SEED_LLM_REASONING_EFFORT", "CODEAGENT_LLM_REASONING_EFFORT")
LLM_SEPARATE_REASONING: Tuple[str, ...] = ("SEED_LLM_SEPARATE_REASONING", "CODEAGENT_LLM_SEPARATE_REASONING")
LLM_CHAT_TEMPLATE_KWARGS: Tuple[str, ...] = ("SEED_LLM_CHAT_TEMPLATE_KWARGS", "CODEAGENT_LLM_CHAT_TEMPLATE_KWARGS")
LLM_EXTRA_BODY: Tuple[str, ...] = ("SEED_LLM_EXTRA_BODY", "CODEAGENT_LLM_EXTRA_BODY")
LLM_CONTEXT_SIZE: Tuple[str, ...] = ("SEED_LLM_CONTEXT_SIZE", "CODEAGENT_LLM_CONTEXT_SIZE")
LLM_INPUT_TOKEN_EST_DIVISOR: Tuple[str, ...] = (
    "SEED_LLM_INPUT_TOKEN_EST_DIVISOR",
    "CODEAGENT_LLM_INPUT_TOKEN_EST_DIVISOR",
)
LLM_CONTEXT_MARGIN: Tuple[str, ...] = ("SEED_LLM_CONTEXT_MARGIN", "CODEAGENT_LLM_CONTEXT_MARGIN")
LLM_BASEURL: Tuple[str, ...] = ("SEED_LLM_BASEURL", "CODEAGENT_LLM_BASEURL")
LLM_MODEL: Tuple[str, ...] = ("SEED_LLM_MODEL", "CODEAGENT_LLM_MODEL")
LLM_SEND_REASONING_CONTENT: Tuple[str, ...] = (
    "SEED_LLM_SEND_REASONING_CONTENT",
    "CODEAGENT_LLM_SEND_REASONING_CONTENT",
)
ASSISTANT_TOOLCALL_PLACEHOLDER_DISABLE: Tuple[str, ...] = (
    "SEED_ASSISTANT_TOOLCALL_PLACEHOLDER_DISABLE",
    "CODEAGENT_ASSISTANT_TOOLCALL_PLACEHOLDER_DISABLE",
)
ASSISTANT_TOOLCALL_PLACEHOLDER: Tuple[str, ...] = (
    "SEED_ASSISTANT_TOOLCALL_PLACEHOLDER",
    "CODEAGENT_ASSISTANT_TOOLCALL_PLACEHOLDER",
)
LLM_MAX_REQUEST_BODY_BYTES: Tuple[str, ...] = (
    "SEED_LLM_MAX_REQUEST_BODY_BYTES",
    "CODEAGENT_LLM_MAX_REQUEST_BODY_BYTES",
)
TOOL_OUTPUT_MAX_CHARS: Tuple[str, ...] = ("SEED_TOOL_OUTPUT_MAX_CHARS", "CODEAGENT_TOOL_OUTPUT_MAX_CHARS")

SESSION_DIR: Tuple[str, ...] = ("SEED_SESSION_DIR", "CODEAGENT_SESSION_DIR")

AGENT_ID: Tuple[str, ...] = ("SEED_AGENT_ID", "CODEAGENT_AGENT_ID")

SAFETY_BASH_BLOCKED: Tuple[str, ...] = ("SEED_SAFETY_BASH_BLOCKED", "CODEAGENT_SAFETY_BASH_BLOCKED")
SAFETY_BASH_ALLOWED_DIRS: Tuple[str, ...] = (
    "SEED_SAFETY_BASH_ALLOWED_DIRS",
    "CODEAGENT_SAFETY_BASH_ALLOWED_DIRS",
)
SAFETY_BASH_TIMEOUT_MAX: Tuple[str, ...] = (
    "SEED_SAFETY_BASH_TIMEOUT_MAX",
    "CODEAGENT_SAFETY_BASH_TIMEOUT_MAX",
)
SAFETY_AUDIT_LOG: Tuple[str, ...] = ("SEED_SAFETY_AUDIT_LOG", "CODEAGENT_SAFETY_AUDIT_LOG")

SAFETY_REDACT_SECRETS: Tuple[str, ...] = ("SEED_SAFETY_REDACT_SECRETS", "CODEAGENT_SAFETY_REDACT_SECRETS")
SAFETY_REDACT_PII: Tuple[str, ...] = ("SEED_SAFETY_REDACT_PII", "CODEAGENT_SAFETY_REDACT_PII")

CRON: Tuple[str, ...] = ("SEED_CRON", "CODEAGENT_CRON")
CRON_TZ: Tuple[str, ...] = ("SEED_CRON_TZ", "CODEAGENT_CRON_TZ")
CHAT_USER_ROUNDS: Tuple[str, ...] = ("SEED_CHAT_USER_ROUNDS", "CODEAGENT_CHAT_USER_ROUNDS")
MEMORY_LOG: Tuple[str, ...] = ("SEED_MEMORY_LOG", "CODEAGENT_MEMORY_LOG")
CRON_EXPERIENCE_SKIP_DUPLICATE: Tuple[str, ...] = (
    "SEED_CRON_EXPERIENCE_SKIP_DUPLICATE",
    "CODEAGENT_CRON_EXPERIENCE_SKIP_DUPLICATE",
)
CRON_EXPERIENCE_TTL_SECONDS: Tuple[str, ...] = (
    "SEED_CRON_EXPERIENCE_TTL_SECONDS",
    "CODEAGENT_CRON_EXPERIENCE_TTL_SECONDS",
)

MEMORY_INJECT: Tuple[str, ...] = ("SEED_MEMORY_INJECT", "CODEAGENT_MEMORY_INJECT")
MEMORY_INJECT_MAX_CHARS: Tuple[str, ...] = ("SEED_MEMORY_INJECT_MAX_CHARS", "CODEAGENT_MEMORY_INJECT_MAX_CHARS")
MEMORY_INJECT_SESSION_ONLY: Tuple[str, ...] = (
    "SEED_MEMORY_INJECT_SESSION_ONLY",
    "CODEAGENT_MEMORY_INJECT_SESSION_ONLY",
)

TRANSCRIPT: Tuple[str, ...] = ("SEED_TRANSCRIPT", "CODEAGENT_TRANSCRIPT")

WEBHOOK_DEDUP: Tuple[str, ...] = ("SEED_WEBHOOK_DEDUP", "CODEAGENT_WEBHOOK_DEDUP")
WEBHOOK_DEDUP_TTL_SEC: Tuple[str, ...] = ("SEED_WEBHOOK_DEDUP_TTL_SEC", "CODEAGENT_WEBHOOK_DEDUP_TTL_SEC")
WEBHOOK_DEDUP_MAX_KEYS: Tuple[str, ...] = ("SEED_WEBHOOK_DEDUP_MAX_KEYS", "CODEAGENT_WEBHOOK_DEDUP_MAX_KEYS")

CONTEXT_COMPACT: Tuple[str, ...] = ("SEED_CONTEXT_COMPACT", "CODEAGENT_CONTEXT_COMPACT")
CONTEXT_COMPACT_SUMMARIZER_BASEURL: Tuple[str, ...] = (
    "SEED_CONTEXT_COMPACT_SUMMARIZER_BASEURL",
    "CODEAGENT_CONTEXT_COMPACT_SUMMARIZER_BASEURL",
)
CONTEXT_COMPACT_SUMMARIZER_MODEL: Tuple[str, ...] = (
    "SEED_CONTEXT_COMPACT_SUMMARIZER_MODEL",
    "CODEAGENT_CONTEXT_COMPACT_SUMMARIZER_MODEL",
)
CONTEXT_COMPACT_MIN_BYTES: Tuple[str, ...] = ("SEED_CONTEXT_COMPACT_MIN_BYTES", "CODEAGENT_CONTEXT_COMPACT_MIN_BYTES")
CONTEXT_COMPACT_MIN_ROUNDS: Tuple[str, ...] = (
    "SEED_CONTEXT_COMPACT_MIN_ROUNDS",
    "CODEAGENT_CONTEXT_COMPACT_MIN_ROUNDS",
)
CONTEXT_COMPACT_KEEP_USER_ROUNDS: Tuple[str, ...] = (
    "SEED_CONTEXT_COMPACT_KEEP_USER_ROUNDS",
    "CODEAGENT_CONTEXT_COMPACT_KEEP_USER_ROUNDS",
)
CONTEXT_SUMMARIZER_MAX_INPUT: Tuple[str, ...] = (
    "SEED_CONTEXT_SUMMARIZER_MAX_INPUT",
    "CODEAGENT_CONTEXT_SUMMARIZER_MAX_INPUT",
)
CONTEXT_COMPACT_WARN_RATIO: Tuple[str, ...] = (
    "SEED_CONTEXT_COMPACT_WARN_RATIO",
    "CODEAGENT_CONTEXT_COMPACT_WARN_RATIO",
)
INLINE_TOOL_PARSE: Tuple[str, ...] = ("SEED_INLINE_TOOL_PARSE", "CODEAGENT_INLINE_TOOL_PARSE")

SYSTEM_PROMPT: Tuple[str, ...] = ("SEED_SYSTEM_PROMPT", "CODEAGENT_SYSTEM_PROMPT")
PERSONA_MEMORY_MAX_CHARS: Tuple[str, ...] = (
    "SEED_PERSONA_MEMORY_MAX_CHARS",
    "CODEAGENT_PERSONA_MEMORY_MAX_CHARS",
)

SESSION_TITLE_MAX_CHARS: Tuple[str, ...] = ("SEED_SESSION_TITLE_MAX_CHARS", "CODEAGENT_SESSION_TITLE_MAX_CHARS")
SESSION_TITLE_MAX_TOKENS: Tuple[str, ...] = ("SEED_SESSION_TITLE_MAX_TOKENS", "CODEAGENT_SESSION_TITLE_MAX_TOKENS")
SESSION_TITLE_LLM: Tuple[str, ...] = ("SEED_SESSION_TITLE_LLM", "CODEAGENT_SESSION_TITLE_LLM")
SESSION_TITLE_MODE: Tuple[str, ...] = ("SEED_SESSION_TITLE_MODE", "CODEAGENT_SESSION_TITLE_MODE")

BROWSER_UNHEALTHY_THRESHOLD: Tuple[str, ...] = (
    "SEED_BROWSER_UNHEALTHY_THRESHOLD",
    "CODEAGENT_BROWSER_UNHEALTHY_THRESHOLD",
)
BROWSER_CDP_UNHEALTHY_THRESHOLD: Tuple[str, ...] = (
    "SEED_BROWSER_CDP_UNHEALTHY_THRESHOLD",
    "CODEAGENT_BROWSER_CDP_UNHEALTHY_THRESHOLD",
)
BROWSER_ALLOW_REMOTE_DEBUG: Tuple[str, ...] = (
    "SEED_BROWSER_ALLOW_REMOTE_DEBUG",
    "CODEAGENT_BROWSER_ALLOW_REMOTE_DEBUG",
)
BROWSER_ALLOW_PRIVATE_URLS: Tuple[str, ...] = (
    "SEED_BROWSER_ALLOW_PRIVATE_URLS",
    "CODEAGENT_BROWSER_ALLOW_PRIVATE_URLS",
)


def project_root_env_raw() -> str:
    return pick_nonempty(*PROJECT_ROOT)
